const translations={
  en:{announcement:"Thoughtfully curated cakes & flowers in the UAE.",navCollections:"Collections",navSignature:"Signature Box",navStory:"Our Story",navOrder:"Order",heroEyebrow:"CAKES · FLOWERS · BEAUTIFUL MOMENTS",heroTitle:"Made to be<br><em>remembered.</em>",heroText:"Elegant cake and flower gifts, thoughtfully composed for birthdays, thank-yous and the moments that deserve something special.",heroCta:"Create your gift",heroSecondary:"Explore collections <span>↘</span>",heroNote:"A cake. Fresh flowers. One beautiful box.",value1:"ELEGANCE",value2:"QUALITY",value3:"SIMPLICITY",value4:"CARE",collectionEyebrow:"THE LOREA EDIT",collectionTitle:"Choose the feeling.",collectionIntro:"Minimal, romantic and refined — designed to look as memorable as the moment feels.",card1Title:"Cake & Roses",card1Text:"Our signature pairing in one elegant gift.",card2Title:"Celebration Cakes",card2Text:"Soft details for birthdays and beautiful milestones.",card3Eyebrow:"YOUR GIFT, YOUR WAY",card3Title:"Choose a flavor. Add roses. Make it personal.",flavorChocolate:"Chocolate",flavorVanilla:"Vanilla",flavorCaramel:"Caramel",flavorLotus:"Lotus",customizeLink:"Customize a gift <span>↘</span>",signatureEyebrow:"THE SIGNATURE BOX",signatureTitle:"Two gestures.<br>One gift.",signatureText:"A handcrafted cake and fresh roses presented together in LOREA’s signature ivory box, finished with sage ribbon and a personal message.",point1:"Choose your cake flavor",point2:"Select the occasion",point3:"Add your personal note",signatureCta:"Build your box",storyEyebrow:"OUR STORY",storyQuote:"“A beautiful gift doesn’t need to be loud. It only needs to feel considered.”",storyText:"LOREA is a modern UAE gifting brand built around elegant simplicity. Every cake, flower and detail is chosen to create a gift that feels personal, polished and easy to remember.",orderEyebrow:"CREATE YOUR GIFT",orderTitle:"A few choices.<br>One beautiful message.",orderIntro:"Build a simple order brief below. We’ll turn your selections into a ready-to-send WhatsApp message.",labelOccasion:"Occasion",labelFlavor:"Cake flavor",labelFlowers:"Flowers",labelMessage:"Card message",orderButton:"Create WhatsApp message",formNote:"No payment is taken on this website."},
  ar:{announcement:"كيك وورود منسّقة بعناية في الإمارات.",navCollections:"التشكيلات",navSignature:"بوكس لوريا",navStory:"قصتنا",navOrder:"اطلب",heroEyebrow:"كيك · ورد · لحظات جميلة",heroTitle:"هدية صُنعت<br><em>لتُتذكّر.</em>",heroText:"هدايا كيك وورد أنيقة، منسّقة بعناية لأعياد الميلاد، الشكر، وكل لحظة تستحق شيئًا مميزًا.",heroCta:"صمّم هديتك",heroSecondary:"اكتشف التشكيلات <span>↙</span>",heroNote:"كيك. ورد طبيعي. بوكس واحد جميل.",value1:"أناقة",value2:"جودة",value3:"بساطة",value4:"اهتمام",collectionEyebrow:"اختيارات لوريا",collectionTitle:"اختر الإحساس.",collectionIntro:"بسيطة، رومانسية وراقية — مصممة لتبقى في الذاكرة مثل اللحظة نفسها.",card1Title:"كيك وورد",card1Text:"توقيع لوريا الكلاسيكي في هدية واحدة أنيقة.",card2Title:"كيك المناسبات",card2Text:"تفاصيل ناعمة لأعياد الميلاد واللحظات الجميلة.",card3Eyebrow:"هديتك بطريقتك",card3Title:"اختر النكهة. أضف الورد. واجعلها شخصية.",flavorChocolate:"شوكولا",flavorVanilla:"فانيلا",flavorCaramel:"كراميل",flavorLotus:"لوتس",customizeLink:"خصّص هديتك <span>↙</span>",signatureEyebrow:"بوكس لوريا المميز",signatureTitle:"لفتتان.<br>هدية واحدة.",signatureText:"كيك محضّر بعناية مع ورود طبيعية داخل بوكس لوريا العاجي، بشريط أخضر سيج ورسالة شخصية.",point1:"اختر نكهة الكيك",point2:"حدّد المناسبة",point3:"أضف رسالتك الخاصة",signatureCta:"صمّم البوكس",storyEyebrow:"قصتنا",storyQuote:"«الهدية الجميلة لا تحتاج أن تكون صاخبة، يكفي أن تشعر بأنها مختارة بعناية.»",storyText:"لوريا براند هدايا عصري في الإمارات قائم على الأناقة البسيطة. كل كيكة ووردة وتفصيل مختار ليصنع هدية شخصية، راقية، وسهلة التذكر.",orderEyebrow:"صمّم هديتك",orderTitle:"خيارات بسيطة.<br>ورسالة جميلة.",orderIntro:"اختر التفاصيل أدناه وسنجهز لك رسالة واتساب جاهزة للإرسال.",labelOccasion:"المناسبة",labelFlavor:"نكهة الكيك",labelFlowers:"الورد",labelMessage:"رسالة الكرت",orderButton:"أنشئ رسالة واتساب",formNote:"لا يتم تحصيل أي دفعة من خلال هذا الموقع."}
};

const selectOptions={
  en:{occasion:["Birthday","Thank You","Anniversary","Just Because","Other"],flavor:["Chocolate","Vanilla","Caramel","Lotus"],flowers:["Signature Roses","More Roses","No Flowers"]},
  ar:{occasion:["عيد ميلاد","شكراً","ذكرى سنوية","بدون مناسبة","أخرى"],flavor:["شوكولا","فانيلا","كراميل","لوتس"],flowers:["ورد لوريا المميز","ورد إضافي","بدون ورد"]}
};
function fillSelect(id,items){const el=document.getElementById(id);const oldIndex=el.selectedIndex;el.innerHTML=items.map(v=>`<option>${v}</option>`).join('');el.selectedIndex=Math.max(0,Math.min(oldIndex,items.length-1));}
const langButton=document.querySelector('.lang-toggle');
const menuButton=document.querySelector('.menu-toggle');
const nav=document.querySelector('.nav');
let lang=localStorage.getItem('lorea-lang')||'en';
function applyLanguage(next){lang=next;localStorage.setItem('lorea-lang',lang);document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(translations[lang][key]) el.innerHTML=translations[lang][key]});langButton.textContent=lang==='en'?'AR':'EN';menuButton.textContent=lang==='en'?'Menu':'القائمة';document.getElementById('message').placeholder=lang==='en'?'Write a short message...':'اكتب رسالة قصيرة...';fillSelect('occasion',selectOptions[lang].occasion);fillSelect('flavor',selectOptions[lang].flavor);fillSelect('flowers',selectOptions[lang].flowers)}
applyLanguage(lang);langButton.addEventListener('click',()=>applyLanguage(lang==='en'?'ar':'en'));menuButton.addEventListener('click',()=>{const isOpen=nav.classList.toggle('open');menuButton.setAttribute('aria-expanded',isOpen)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
document.getElementById('year').textContent=new Date().getFullYear();
const toast=document.querySelector('.toast');function showToast(text){toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2500)}
document.getElementById('orderForm').addEventListener('submit',e=>{e.preventDefault();const occasion=document.getElementById('occasion').value,flavor=document.getElementById('flavor').value,flowers=document.getElementById('flowers').value,message=document.getElementById('message').value.trim();const text=lang==='ar'?`مرحباً LOREA، أود طلب هدية.%0Aالمناسبة: ${occasion}%0Aنكهة الكيك: ${flavor}%0Aالورد: ${flowers}%0Aرسالة الكرت: ${message||'-'}`:`Hello LOREA, I would like to order a gift.%0AOccasion: ${occasion}%0ACake flavor: ${flavor}%0AFlowers: ${flowers}%0ACard message: ${message||'-'}`;window.open(`https://wa.me/?text=${encodeURIComponent(decodeURIComponent(text))}`,'_blank','noopener');showToast(lang==='ar'?'تم تجهيز رسالة الطلب':'Your order message is ready')});